const feathers = require('feathers/client');
const rest = require('feathers-rest/client');
const superagent = require('superagent');
const hooks = require('feathers-hooks');
const auth = require('feathers-authentication-client');

const user = {
  name: 'Will Fris',
  email: 'admin@admin.com',
  password: 'qwerty1',
  admin: true,
};


const recipes = [{
  title: 'Broccoli-courgettesoep',
  picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_15_ZAT_LUNCH_Broccoli-courgette-soep.jpg',
  persons: 4,
  ingredients: [
    { amount: 2,
      measure: 'el',
      ingredient: 'olijfolie'},
    { amount: 1,
      ingredient: 'rode ui, fijngesneden'},
    { amount: 1,
      ingredient: 'courgette'},
    { amount: 300,
      measure: 'g',
      ingredient: 'broccoliroosjes'},
    { amount: 750,
      measure: 'ml',
      ingredient: 'water'},
    { amount: 1.5,
      ingredient: 'tuinkruidenbouillontablet'},
    { amount: 1,
      measure: 'bosje',
      ingredient: 'verse munt'}
  ],
  lunch: true,
  appetizer: true,
  dinner: true,
  nuts: true,
  gluten: true,
  sugar: true,
  soy: true,
  lessThanFifteen: true,
  description: 'Deze groene soep heb je in een handomdraai op tafel. Een makkelijke manier om veel groenten binnen te krijgen!',
  cookingSteps: 'Verhit de olijfolie en fruit de ui 3 minuten. Bak de courgette 5 min. mee. Voeg de broccoli, water, bouillontablet en munt toe. Laat 4 min. zacht koken. Pureer met een staafmixer. Breng op smaak met peper en zout.',
  tip: 'voor een vollere soep kun je een kopje (ongezouten) cashewnoten 2 uur laten weken, afgieten en met de soep mee pureren. Ook kan je wat rijstmelkroom of sojaroom mee pureren.'
},{
  title: 'Pompoen Pindastoofpot',
  picture: 'https://veganchallenge.nl/wp-content/uploads/2013/09/NOV_1_VRIJ_AVOND_Pompoen-pindastoofpot.jpg',
  persons: 4,
  ingredients: [
    { amount: 250,
      measure: 'gr',
      ingredient: 'zilvervliesrijst of quinoa'},
    { amount: 1,
      measure: 'el',
      ingredient: 'zonnebloemolie'},
    { amount: 1,
      ingredient: 'ui, fijngesneden'},
    { amount: 1,
      ingredient: 'teen knoflook'},
    { amount: 1,
      ingredient: 'wortel, in blokjes'},
    { amount: 600,
      measure: 'gr',
      ingredient: 'pompoen'},
    { amount: 400,
      measure: 'gr',
      ingredient: ' blik tomatenblokjes op sap'},
    { amount: 75,
      measure: 'gr',
      ingredient: 'pindakaas met stukjes'},
    { amount: 2,
      measure: 'el',
      ingredient: 'sojasaus'},
    { amount: 1,
      measure: 'el',
      ingredient: 'kerriepoeder'},
    { amount: 0.5,
      measure: 'tl',
      ingredient: 'chilipoeder'},
    { amount: 2,
      measure: 'tl',
      ingredient: 'peterselie'},
    { amount: 500,
      measure: 'ml',
      ingredient: 'groentebouillon'},
    { amount: 1,
      measure: 'blik',
      ingredient: 'kidneybonen uitgelekt'},
    { amount: 150,
      measure: 'gr',
      ingredient: 'tuinerwten (diepvries)'},
    { amount: 50,
      measure: 'gr',
      ingredient: 'dry roasted peanuts '},
  ],
  dinner: true,
  westAfrican: true,
  autumn: true,
  thirtyToOneHour: true,
  description: 'Als het aan onze receptontwikkelaar Alynda ligt, gaat er bijna dagelijks wel pindakaas door één van de VeganChallenge recepten. Aangezien niet iedereen dat even lekker vindt, houden we het beperkt, maar dit recept is een goed voorbeeld dat het soms wel heel lekker kan zijn. Geïnspireerd door de Afrikaanse keuken, waar pinda en pompoen een klassieke combi zijn! NB: check even of je dry roasted peanuts vegan zijn, dit is meestal wel zo.',
  cookingSteps: 'Kook de rijst/quinoa volgens de gebruiksaanwijzing op de verpakking. Verhit de olie in een ruime pan en smoor de ui 3-5 minuten met de deksel op de pan. Pers de knoflook erboven uit en voeg de wortel en pompoen toe. Bak dit nog 5 minuten, roer tussendoor. Voeg de tomatenblokjes, pindakaas, sojasaus, kerrie, chilipoeder, peterselie en bouillon toe. Roer goed door, breng aan de kook, zet het vuur laag en laat 20 minuten zachtjes stoven. Voeg in de laatste 5 minuten de kidneybonen en tuinerwten toe. Serveer de stoofpot met de rijst of quinoa, bestrooid met de pinda’s.',
  tip: 'bij sommige supermarkten kun je pompoen uit de vriezer kopen, is wat duurder maar scheelt een boel snijwerk. Halveer dan de hoeveelheid bouillon.'
},{
  title: 'Paprika’s gevuld met groene spaghetti',
  picture: 'https://veganchallenge.nl/wp-content/uploads/2016/10/Spaghetti_Paprika-730x450.jpg',
  persons: 4,
  ingredients: [
    { amount: 75,
      measure: 'g',
      ingredient: 'cashewnoten'},
    { ingredient: 'water'},
    { amount: 200,
      measure: 'g',
      ingredient: '(volkoren) spaghetti'},
    { amount: 4,
      ingredient: 'oranje paprikas'},
    { amount: 2,
      measure: 'el',
      ingredient: 'pesto'},
    { amount: 60,
      measure: 'g',
      ingredient: '(grote hand) spinazie'},
    { amount: 1,
      measure: 'klein teentje',
      ingredient: 'knoflook, gepeld'},
    { amount: 1,
      ingredient: 'kleine avocado'},
    { amount: 4,
      measure: 'el',
      ingredient: 'edelgist (optioneel)'}
  ],
  appetizer: true,
  dinner: true,
  italian: true,
  halloween: true,
  autumn: true,
  sugar: true,
  soy: true,
  thirtyToOneHour: true,
  description: 'Dit gevulde paprikarecept is perfect voor een Halloweenfeestje, maar natuurlijk ook voor een sfeervol Halloweendiner thuis. Serveer dit als voor- of bijgerecht of eet ze samen met monsterburgers voor een meer complete maaltijd.',
  cookingSteps: 'Doe de cashewnoten in een schaaltje en voeg 300 ml kokend water toe. Zet opzij. Breng een grote pan water aan de kook en kook de spaghetti volgens de verpakking. Snijd ondertussen gezichtjes uit de paprika’s. Als je niet van rauwe paprika houdt kun je ze in de oven op 200 graden zo’n 20 minuten bakken op bakpapier. Doe de pesto, spinazie, knoflook, avocado en edelgist in een blender of keukenmachine. Voeg de cashewnoten samen met het water waarin ze zijn geweekt toe en blend het geheel tot een gladde saus. Meng de saus door de spaghetti en vul de paprika’s ermee.'
},{
  title: 'Groene tosti',
  picture: 'https://veganchallenge.nl/wp-content/uploads/2013/01/FEB16-ZAT-LUNCH-Groenste-tosti-768x961.jpg',
  persons: 1,
  ingredients: [
    { amount:2,
      measure: 'sneetjes',
      ingredient: 'brood'},
    { amount: 3,
      measure: 'tl',
      ingredient: 'kaasvrije pesto' },
    { amount:6,
      measure: 'blaadjes',
      ingredient: 'spinazie'},
    { amount: 1,
      measure: 'kwart',
      ingredient: 'Avocado, in dunne plakjes gesneden'},
    { ingredient: 'Zout en peper' },
    { amount:2,
      measure: 'el',
      ingredient: 'edelgist (optioneel)'},
  ],
  breakfast: true,
  french: true,
  valentine: true,
  birthday: true,
  highTea: true,
  easter: true,
  halloween: true,
  sinterklaas: true,
  christmas: true,
  spring: true,
  summer: true,
  autumn: true,
  winter: true,
  lessThanFifteen: true,
  description: 'Een makkelijke, super gezonde en plantaardige variant van de kaastosti. Door de edelgist behoudt de tosti zijn kaas-achtige smaak. Door de extra groenten heeft de tosti meer bite en textuur. Ook lekker voor mee naar school of werk. Kaasvrije pesto is bijvoorbeeld verkrijgbaar van AH Puur&Eerlijk, maar je kan het ook zelf maken door bijvoorbeeld basilicum met olie of notenpasta te mengen.',
  cookingSteps: 'Besmeer één snee brood met de pesto. Leg hierbovenop de blaadjes spinazie en de plakjes avocado. Voeg zout, peper en edelgist toe en leg het andere sneetje brood erbovenop. Laat de tosti bruin en knapperig worden in een tosti ijzer.',
  tip: 'Serveer met ketchup of tomatensalsa!',
},
{
  title: 'Carrot cupcakes',
  picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_8_ZAT_BAK_Carrot-cake.jpg',
  persons: 24,
  ingredients: [
    { amount: 500,
      measure: 'ml',
      ingredient: 'sinaasappelsap'},
    { amount: 150,
      measure: 'ml',
      ingredient: 'olie'},
    { amount: 200,
      measure: 'g',
      ingredient: 'suiker'},
    { amount: 50,
      measure: 'g',
      ingredient: 'walnoten'},
    { amount: 50,
      measure: 'g',
      ingredient: 'rozijnen'},
    { amount: 1,
      measure: 'tl',
      ingredient: 'nootmuskaat'},
    { amount: 1,
      measure: 'tl',
      ingredient: 'kaneel'},
    { amount: 1,
      measure: 'tl',
      ingredient: 'speculaaskruiden'},
    { amount: 400,
      measure: 'g',
      ingredient: 'volkorenmeel'},
    { amount: 1,
      measure: 'zakje',
      ingredient: 'bakpoeder'},
    { amount: 0.5,
      measure: 'tl',
      ingredient: 'zout'},
    { amount: 250,
      measure: 'g',
      ingredient: 'geraspte wortels'}
  ],
  dessert: true,
  soy: true,
  thirtyToOneHour: true,
  description: 'Hoeveel grapjes je ook over wortels en konijnenvoer kunt bedenken, deze cake wil je zeker zelf opeten! Carrot cake komt oorspronkelijk uit Amerika, maar je kunt dit recept gewoon maken met ingrediënten uit de supermarkt.',
  cookingSteps: 'Verwarm de oven voor op 175 graden. Voeg in een kom of maatbeker de sinaasappelsap, olie, suiker en vanille extract samen. Hak de walnoten in stukken en doe deze samen met de rozijnen, nootmuskaat, kaneel speculaaskruiden, volkorenmeel, bakpoeder en zout in een ruime kom.  Schil eventueel de wortels en rasp ze fijn. Voeg de vloeibare ingrediënten al mixend bij de droge ingrediënten en meng goed. Voeg tenslotte de wortel toe. Verdeel het beslag over 24 cupcake vormpjes of vul er een cakeblik (30 cm) of taartvorm (Ø 24 cm) mee, en bak, afhankelijk van de vorm, 25 tot 65 minuten.',
  tip: 'Voor nog meer verwennerij kun je een heerlijk romig glazuur maken van vegan margarine (100 g), poedersuiker(150 g) en vanille om een laagje op de taart te maken. Je kunt zelfs kleine worteltjes van oranje en groene marsepein maken voor er bovenop.'
},
{
title: 'Pindasoep',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_25_DIN_AVOND_Pindasoep.jpg',
persons: 4,
ingredients: [
  { amount: 1,
    ingredient: 'grote ui'},
  { amount: 2,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { amount: 2,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { amount: 4,
    ingredient: 'aardappelen'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'olie'},
  { amount: 300,
    measure: 'gram',
    ingredient: 'gesneden prei'},
  { amount: 1,
    measure: 'liter',
    ingredient: 'groentebouillon'},
  { amount: 150,
    measure: 'gram',
    ingredient: 'pindakaas'},
  { amount: 4,
    measure: 'eetlepels',
    ingredient: 'ketjap manis'},
  { amount: 2,
    measure: 'theelepels',
    ingredient: 'sambal oelek'},
  { ingredient: 'Zout en peper'},
],
spring: true,
summer: true,
autumn: true,
winter: true,
dinner: true,
fifteenToThirty: true,
description: 'Deze soep is lekker romig door de aardappel en pindakaas. Je kunt hem zo pittig maken als je zelf lekker vindt!',
cookingSteps:'Pel de ui en de knoflook en snipper ze. Was en schil de aardappelen en snijd ze in blokjes van circa 1 centimeter. Snijd en was de prei. Verhit de olie in een pan en bak de ui en knoflook ongeveer 1 minuut. Voeg de prei toe en bak die ongeveer 2 min mee. Schenk de bouillon in de pan en voeg de aardappelblokjes toe. Breng het geheel aan de kook en laat de soep zachtjes ongeveer 10 min koken tot de aardappels gaar zijn. Roer de pindakaas en de ketjap door de soep en breng het geheel op smaak met sambal, zout en peper.',
tip: ' Je kunt de pindasoep serveren met rijst voor een goed vullende avondmaaltijd. Ook lekker om pindakaas met stukjes pinda te gebruiken!',
},
{
title: 'Pittige pompoensoep',
picture: 'https://veganchallenge.nl/wp-content/uploads/2014/10/31_10_DIN_Pittige-pompoensoep.jpg',
persons: 4,
ingredients: [
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'olie'},
  { amount: 1,
    ingredient: 'rood pepertje, in ringetjes'},
  { amount: 1,
    ingredient: 'grote ui, gesnipperd'},
  { amount: 1,
    ingredient: 'rode paprika, in blokjes'},
  { amount: 1,
    ingredient: 'kleine flespompoen, in blokjes'},
  { amount: 1,
    measure: 'blik',
    ingredient: 'gepelde tomaten'},
  { amount: 1,
    ingredient: 'laurierblad'},
  { amount: 750,
    measure: 'ml',
    ingredient: 'water'},
  { amount: 2,
    ingredient: 'groentebouillonblokjes'},
  { amount: 1,
    ingredient: 'paprikapoeder'},
],
gluten: true,
soy: true,
nuts: true,
autumn: true,
italian: true,
lunch: true,
appetizer: true,
fifteenToThirty: true,
description: 'Perfecte soep voor door de week, snel klaar en pittig.',
cookingSteps:'Verhit in een grote pan de olie en voeg het pepertje, de ui, paprika en pompoen toe. Roerbak een paar minuten. Voeg tomaten, laurier, water en bouillonblokjes toe en breng aan de kook. Kook ongeveer 15 minuten, totdat de groenten gaar zijn. Verwijder de laurier en voeg de paprikapoeder toe. Pureer met een blender of staafmixer en serveer.',
tip: 'lekker met vers brood met bv. humus. Ook lekker is het een hand fijngesneden peterselie over de soep te strooien.',
},
{
title: 'Vegan kaasvlinders',
picture: 'https://veganchallenge.nl/wp-content/uploads/2016/03/Vegan-Kaasvlinders-730x450.jpg',
persons: 5-6,
ingredients: [
  { amount: 270,
    measure: 'gr',
    ingredient: 'vegan bladerdeeg (bijv. Tante Fanny* of AH vers bladerdeeg)'},
  { amount: 100,
    measure: 'gr',
    ingredient: 'vegan kaas, zoals Wilmersburger'},
  { amount: 3,
    measure: 'tl',
    ingredient: 'kerriepoeder (bijvoorbeeld madras)'},
  { ingredient: 'zout naar smaak'},
],
nuts: true,
highTea: true,
lunch: true,
brunch:true,
dinner: true,
snacks: true,
fifteenToThirty: true,
description: 'Als vegan kaascroissantjes blijven eten? Het kan! Deze variant met vegan kaas is makkelijk en snel klaar te maken en bovendien geheel supermarktfriendly. Jumbo heeft in sommige filialen plantaardige kaasproducten van het merk Wilmersburger vast in het assortiment en kan het anders op aanvraag bestellen. Wil je wat andere merken proberen dan kun je terecht bij natuurwinkels of online webshops gespecialiseerd in vegan producten.',
cookingSteps:'Verwarm de oven op 180 graden (gasoven) of 165 graden (heteluchtoven). Zet een bakplaat, een plank, rasp, scherp mes en de ingrediënten klaar. Rol het deeg uit en leg het zonder het bijgeleverde bakpapier op de plank. Leg het deeg met de lange kant naar je toe. Leg het bakpapier op de bakplaat. Rasp een flinke laag kaas over het deeg. Bestrooi met wat kerriepoeder en eventueel met wat zout. Rol de deeglap vanaf twee kanten tot de helft op. Snij rolletjes van 2 cm van het deeg. Leg ze wat uit elkaar op de bakplaat. Strooi er nog wat kaas over en bak ongeveer 20/25 minuten tot ze goudbruin en knapperig zijn.',
tip: 'neem eens een kijkje bij de webshops van Veggie4U en Veggiedeli.',
},
{
title: 'Oranje Falafel',
picture: 'https://veganchallenge.nl/wp-content/uploads/2014/03/APR_26_ZAT_LUNCH-Oranje-falafel.jpg',
persons: 4,
ingredients: [
  { amount: 250,
    measure: 'gr',
    ingredient: 'gedroogde kikkererwten*'},
  { amount: 500,
    measure: 'gr',
    ingredient: 'zoete aardappel'},
  { amount: 1,
    measure: 'bosje',
    ingredient: 'verse peterselie, gehakt'},
  { amount: 1,
    measure: 'bosje',
    ingredient: 'verse koriander, gehakt'},
  { amount: 1.5,
    measure: 'theelepel',
    ingredient: 'komijnpoeder'},
  { amount: 0.75,
    measure: 'theelepel',
    ingredient: 'zout'},
  { ingredient: 'peper uit de molen'},
  { amount: 2,
    measure: 'tenen',
    ingredient: 'knoflook, gepeld'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'bloem of kikkererwtenmeel'},
  { ingredient: 'olijfolie'},
  ],
  gluten: true,
  soy: true,
  nuts: true,
  sugar: true,
  lunch:true,
  thirtyToOneHour: true,
  description: 'Dit bijzondere falafelrecept kwam van VeganChallenge coördinator Marieke. Hoewel je tegenwoordig falafel bij vrijwel elke supermarkt kunt vinden, is het ook niet moeilijk zelf te maken – en dan kun je er toffe kleurtjes aangeven! Serveer deze falafel met onze oranje hummus  om helemaal in de stemming te komen voor Koningsdag.',
  cookingSteps: 'Week de kikkererwten een nacht in ruim water. Verwarm de oven voor op 200 graden. Pak de zoete aardappel (met schil) in aluminiumfolie in en zet ruim een uur tot anderhalf uur in de oven tot ze gaar zijn. Dit kan je testen door er met een vork in te prikken (ook dit kan je al een dag eerder doen). Laat ze afkoelen. Schil ze en snijd ze vervolgens in grove stukken. Doe de geweekte kikkererwten in de keukenmachine en maal kort, totdat ze grof gemalen zijn. Voeg vervolgens de overige ingrediënten toe en maal tot het een goed gemengd geheel is. Proef goed of er genoeg komijn en genoeg zout in zit. Zet het vervolgens ongeveer een half uurtje weg in de koelkast. Hierdoor wordt het mengsel wat steviger en maak je makkelijker balletjes. Verwarm ondertussen de oven voor op 180 graden. Maak balletjes van het formaat ping-pongbal en druk ze een beetje plat tot schijven van ruim een centimeter dik. Leg bakpapier op een bakplaat en leg de falafels hierop. besprenkel met wat olie en zet het geheel 15 minuten in de oven. Bakken in de koekenpan kan ook. Verhit dan wat olijfolie in een bakpan en bak de falafels 3-4 minuten aan beide kanten op middelhoog vuur. Let op dat ze niet verbranden. Serveer met een sausje van sojayoghurt, citroen, komijnpoeder en verse koriander. Met een pitabroodje en gemengde sla maak je er een echte maaltijd van.',
  tip: 'vervang de zoete aardappel door bieten voor een prachtig roze falafel.',
},
{
title: 'Adukibonensoep met rucolapesto en Turks brood',
picture: 'https://veganchallenge.nl/wp-content/uploads/2016/09/Adukibonensoep-730x450.jpg',
persons: 4,
ingredients: [
  { amount: 3,
    measure: 'stengels',
    ingredient: 'bleekselderij'},
  { amount: 250,
    measure: 'gr',
    ingredient: '(gele) peen'},
  { amount: 2,
    measure: 'stuks',
    ingredient: 'prei'},
  { amount: 2,
    ingredient: 'uien'},
  { amount: 2,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { ingredient: 'olie (om te bakken)'},
  { amount: 1,
    measure: 'blikje',
    ingredient: 'tomatenblokjes'},
  { amount: 1,
    measure: 'blijke',
    ingredient: 'adukibonen'},
  { amount: 500,
    measure: 'ml',
    ingredient: 'water'},
  { amount: 1,
    measure: 'blokje',
    ingredient: 'groentebouillon'},
  { ingredient: 'peper en zout (naar smaak)'},
  { amount: 50,
    measure: 'gr',
    ingredient: 'rucola'},
  { amount: 20,
    measure: 'gr',
    ingredient: 'pijnboompitten'},
  { amount: 1,
    measure: 'teentje',
    ingredient: 'knoflook'},
  { amount: 50,
    measure: 'ml',
    ingredient: 'olijfolie'},
  { ingredient: 'zout (naar smaak)'},
  { amount: 1,
    measure: 'stuk',
    ingredient: 'Turks brood'},
],
lunch: true,
autumn: true,
gluten: true,
soy: true,
sugar: true,
nuts: true,
thirtyToOneHour: true,
description: 'Deze lekkere en goed vullende maaltijdsoep is een gastrecept van De Krat. Tijdens de VeganChallenge leveren zij elke week een uitbundige maaltijdbox vol eerlijke, plantaardige en goede spullen: seizoensproducten, lokaal gekweekt en duurzaam geproduceerd met respect voor mens, dier en milieu.',
cookingSteps:'Snij de bleekselderij en de peen in kleine blokjes en de prei in dunne ringen. Snipper de ui en hak de knoflook fijn. Verhit olie in een grote soeppan met dikke bodem en fruit de groenten, ui en knoflook zachtjes aan. Wanneer de uien glazig zijn, voeg je de tomatenblokjes toe en laat het geheel 15-20 minuten of langer op middelhoog vuur met deksel op de pan zachtjes stoven. Hoe langer, hoe smaakvoller. Breng op smaak met peper en zout. Roer dan de adukibonen er door samen met het water en het bouillonblokje. Breng de soep al roerend aan de kook en laat nog 10 minuten zachtjes doorkoken. Voeg eventueel nog wat water toe als de soep je te dik lijkt. Verwarm de oven voor op 180 graden om het Turks brood zo even in op te piepen, circa 4 minuten. Rooster ondertussen de pijnboompitten in een droge koekenpan, pas op: ze kunnen snel aanbranden! Pureer de waterkers inclusief de steeltjes samen met de pijnboompitten, een fijngehakt klein teentje knoflook en de olijfolie tot een pesto. Breng op smaak met zout. Serveer de soep met de pesto en het brood. De pesto is bedoeld voor in de soep, maar natuurlijk ook heel lekker op het brood!',
tip: 'maak ook eens pesto met waterkers ipv rucola, zoals bij het originele recept op de website van de Krat',
},
{
title: 'Groente Quiche',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_23_ZON_AVOND_Groente-Quiche3.jpg',
persons: 4,
ingredients: [
  { amount: 5,
    measure: 'plakjes',
    ingredient: 'hartige taartdeeg van Koopmans'},
  { amount: 375,
    measure: 'gr',
    ingredient: 'tofu'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'citroensap'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'appelcider azijn'},
  { ingredient: 'handje verse basilicum'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'gedroogde tijm'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'zout'},
  { amount: 0.5,
    measure: 'theelepel',
    ingredient: 'geelwortel (kurkuma)'},
  { ingredient: 'Versgemalen peper'},
  { amount: 1,
    ingredient: 'ui'},
  { amount: 3,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { amount: 250,
    measure: 'gr',
    ingredient: 'champignons'},
  { amount: 1,
    ingredient: 'rode paprika'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'olie'},
  { amount: 200,
    measure: 'gr',
    ingredient: 'verse spinazie'},
  { ingredient: 'Paprikapoeder'},
],
lunch: true,
french: true,
nuts: true,
sugar: true,
moreThanOneHour: true,
description: 'Hoewel het even duurt voor deze quiche op tafel staat, is het lang niet zoveel werk als je misschien zou denken, mede door kant-en-klare deegplakken te gebruiken. Tofu is een perfecte basis voor een plantaardige quiche.',
cookingSteps:'Leg de plakjes deeg uit de vriezer om ze te ontdooien. Verwarm de oven voor op 180ºC. Haal de tofu uit de verpakking en knijp deze goed uit. Doe tofu, citroensap, azijn, tijm, eventueel basilicum, zout en peper naar smaak in de kom van een keukenmachine. Pureer het geheel tot een fijne, gladde pasta. Snijd de ui en knoflook fijn,de paprika in blokjes en de champignon in plakjes. Bak dit een paar minuten op middelhoog vuur.  Voeg de spinazie toe en laat een paar minuten meeslinken. Doe het groentemengsel in een zeef en druk het vocht er zo veel mogelijk uit. Roer het dan door het tofu mengsel. Besmeer een quiche- of taartvorm (Ø 26 cm) met wat olie en bedek de bodem en randen met de plakjes deeg. Schep het groente-tofu mengsel in de vorm, strijk de bovenkant glad en strooi er wat paprikapoeder op. Bak de taart 40 tot 45 minuten en serveer met een salade.',
tip:'Door kala namak (zwart zout) te gebruiken i.p.v. gewoon zout, krijgt de quiche meer een ei-smaak. Dit zout heeft namelijk een hoog zwavelgehalte. Je vindt het bij toko’s en vegan webshops, het is echt de moeite waard voor alle eivervangende gerechten!',
},
{
title: 'Chocoladeijs',
picture: 'https://veganchallenge.nl/wp-content/uploads/2014/09/11_10_DES_Chocoladeijs.jpg',
persons: 4,
ingredients: [
  { amount: 200,
    measure: 'ml',
    ingredient: 'kokosmelk'},
  { amount: 100,
    measure: 'ml',
    ingredient: 'ojaroom (voor sojavrij, gebruik nog eens 100 ml kokosmelk)'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'cacao'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'poedersuiker'},
  { amount: 5,
    measure: 'eetlepels',
    ingredient: 'pure chocoladepasta'},
],
gluten: true,
nuts: true,
soy: true,
dessert: true,
fifteenToThirty: true,
description: 'Niet overal is altijd vegan roomijs voorhanden. Maar met een ijsmachine, die je voor minder dan twee tientjes al in huis hebt, maak je zelf de heerlijkste toetjes in een handomdraai!',
cookingSteps:'Koel de ijsmachine zoals beschreven in de gebruiksaanwijzing. Giet de kokosmelk en sojaroom in een kom en pak een staafmixer of garde erbij. Voeg al mixende beetje bij beetje de cacao en poedersuiker toe zodat je een egaal mengsel overhoudt. Wees niet overenthousiast met de mixsnelheid, anders zit je zelf onder! Voeg hierna de chocoladepasta toe en mix wederom goed. Naar smaak kun je eventueel nog wat extra cacao of poedersuiker toevoegen. Extra cacao maakt het ijs wat heftiger van smaak, extra poedersuiker juist wat zoeter. Zet het mengsel in de koelkast en laat het minimaal een uur afkoelen voor je het in de ijsmachine giet.',
tip:'Dit chocoladeijs is heerlijk met toppings zoals banaan, aardbei, warme kersen, nootjes of vegan slagroom.',
},
{
title: 'Pilav met gefrituurde aubergine',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/06/JUN_28_VRIJ_AVOND_Pilav-met-abrikoos-en-aubergine.jpg',
persons: 4,
ingredients: [
  { amount: 1,
    ingredient: 'grote aubergine'},
  { amount: 2,
    measure: 'theelepels',
    ingredient: 'zout(+/-)'},
  { amount: 200,
    measure: 'ml',
    ingredient: 'zonnebloemolie'},
  { amount: 1,
    ingredient: 'ui, fijngesneden'},
  { amount: 300,
    measure: 'gr',
    ingredient: 'snelkook zilvervliesrijst'},
  { amount: 400,
    measure: 'ml',
    ingredient: 'tomatenblokjes op sap'},
  { amount: 500,
    measure: 'ml',
    ingredient: 'water'},
  { amount: 1,
    ingredient: 'groentebouillontablet'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'gemalen komijn (djintan)'},
  { ingredient: 'snuf kaneelpoeder'},
  { amount: 12,
    ingredient: 'gedroogde abrikozen'},
  { amount: 50,
    measure: 'gr',
    ingredient: 'amandelschaafsel'},
  { amount: 200,
    measure: 'gr',
    ingredient: 'gemengde sla'},
  { amount: 4,
    measure: 'eetlepels',
    ingredient: 'naturel sladressing'},
],
fifteenToThirty: true,
gluten: true,
soy: true,
sugar: true,
nuts: true,
lunch: true,
summer: true,
description: 'Pilav is een rijstgerecht uit het Midden-Oosten, verwant aan de Italiaanse risotto. Je kunt het van verschillende granen maken. Hier hebben we gekozen voor rijst, maar je kunt het ook eens met quinoa bereiden.',
cookingSteps: 'Snijd de aubergine in blokjes van 1-2 cm. Leg de blokjes aubergine in een vergiet en strooi het zout erover, zodat het vocht uit de aubergine trekt. Breng water aan de kook en laat de bouillontabletten hierin oplossen. Verwarm 2 eetlepels van de olie in een pan met dikke bodem en fruit de ui 1 minuut. Meng de rijst erdoor en roer tot de korrels glanzen. Voeg de tomatenblokjes (met sap), komijn, kaneel, water en bouillontablet toe. Snijd de abrikozen in stukjes en meng ze door de rijst. Laat de rijst met het deksel op de pan in circa 15 minuten zachtjes gaarkoken. Roer regelmatig en voeg wat extra water toe indien het droogkookt. Breng de pilav op smaak met zout en peper. Verhit ondertussen de rest van de olie in een ruime koekenpan. Je kunt ook een frituurpan gebruiken. De olie moet heet zijn, maar er mag geen rook vanaf komen, dit is ongeveer 180 graden Celsius. Dep de blokjes aubergine droog met keukenpapier. Frituur ze in de olie rondom goudbruin en krokant, in ongeveer 3 minuten. Laat ze op keukenpapier uitlekken. Verdeel de rijst over de borden en strooi aubergineblokjes en amandelschaafsel erover. Meng in een kom de sla met de dressing en serveer erbij.',
tip:'kun je geen vegan sladressing vinden, of maak je deze liever zelf? Meng dan wat olijfolie, azijn, agavesiroop en saladekruiden.',
},
{
title: 'Spinazieburgers',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_8_ZAT_AVOND_Spinazie-burgers.jpg',
persons: 6,
ingredients: [
  { amount: 100,
    measure: 'gr',
    ingredient: 'zilvervliesrijst (ongekookt)'},
  { amount: 450,
    measure: 'gr',
    ingredient: 'diepvriesspinazie, ontdooid'},
  { amount: 100,
    measure: 'gr',
    ingredient: 'havermout'},
  { amount: 70,
    measure: 'gr',
    ingredient: 'pijnboompitten'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'knoflookpoeder'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'uipoeder'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'mosterdpoeder'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'gedroogde basilicum'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'gedroogde oregano'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'paprikapoeder'},
  { amount: 2,
    measure: 'theelepel',
    ingredient: 'zout'},
  { ingredient: 'Zout en peper naar smaak'},
  { ingredient: '(Sesam)olie om in te bakken'},
],
nuts: true,
soy: true,
sugar: true,
lunch: true,
thirtyToOneHour: true,
description: 'Deze burgers bevatten eenvoudige ingrediënten en zijn toch rijk aan smaak. Niet alle kruiden in huis? Neem dan gewoon wat meer van de andere kruiden. Je krijgt het beste resultaat als je pandan (zilvervlies) rijst voor deze burgers gebruikt, die plakt wat meer dan basmati rijst. Mocht je dat niet hebben, kun je ook wat bloem door het deeg doen.',
cookingSteps: 'Zet de spinazie een avond van te voren vast op een bord in de koelkast, zodat het ruim de tijd heeft om te ontdooien. Als de rijst die je gebruikt niet zo goed blijkt te plakken, kun je wat extra bloem door het deeg doen. Kook de rijst gaar volgens de aanwijzingen op de verpakking en laat 5 minuten afkoelen. Druk in een zeef alle vocht uit de spinazie. Doe samen met de havermout in een ruime kom en laat staan terwijl de rijst kookt. Zodra de rijst klaar is voeg je deze toe aan het spinazie/havermoutmengsel. Voeg pijnboompitten en alle overige ingrediënten toe (behalve de olie). Kneed goed door. Vorm er met je handen 12 burgers van.  Verhit wat olie in een koekenpan en bak de burgers ongeveer 4 minuten per kant, tot ze mooi bruin zijn. Eventueel kun je ze ook in de oven bakken, op 175 graden zo’n 15 minuten per kant.',
tip: 'Vries de ongebakken burgers in, eventueel in een bakpapiertje zodat ze niet aan elkaar gaan plakken. Zo mik je ze op een drukke dag gelijk in de pan en heb je in no-time een gezonde maaltijd op tafel!',
},
{
title: 'Cornflakes met vers fruit',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/01/FEB13-WOE-ONTBIJT-Cornflakes-met-vers-fruit.jpg',
persons: 1,
ingredients: [
  { amount: 250,
    measure: 'ml',
    ingredient: 'rijstmelk, havermelk of andere plantaardige melk'},
  { amount: 1,
    ingredient: 'rijpe banaan'},
  { amount: 50,
    measure: 'gr',
    ingredient: 'kiwi, kakifruit of peer'},
  { amount: 6,
    measure: 'eetlepels',
    ingredient: 'cornflakes'},
],
gluten: true,
soy: true,
sugar: true,
lessThanFifteen: true,
breakfast: true,
description: 'In de supermarkt zijn de meeste cornflakes helemaal plantaardig. Als je geen vitamine D3 wil eten (wat van dierlijke oorsprong is, vitamine D2 is plantaardig), dan moet je er even op letten dat dit niet is toegevoegd. De meeste winkelmerken, die ook nog eens goedkoper zijn, bevatten deze vitamine niet.',
cookingSteps: 'Snijd de banaan in plakjes en de rest van het fruit in stukjes. Doe alle ingrediënten in een kom.',
tip: 'Je kunt eindeloos variëren met verschillende soorten fruit, soorten plantaardige melk of andere ontbijtgranen. Probeer bijvoorbeeld eens All Bran fruit ’n fibre (of een soortgelijk product) in plaats van cornflakes.',
},
{
title: 'Gegrilde paprika’s met risotto vulling',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_30_ZON_AVOND_Gegrilde-paprikas-met-risottovulling-testerfoto-768x577.jpg',
persons: 4,
ingredients: [
  { amount: 4,
    ingredient: 'rode paprika’s (of andere kleuren)'},
  { amount: 4,
    measure: 'eetlepels',
    ingredient: 'geroosterde pijnboompitten'},
],
gluten: true,
sugar: true,
soy: true,
nuts: true,
bbq: true,
italian: true,
lunch: true,
thirtyToOneHour: true,
description: 'Dit feestelijke recept is ideaal als je nog een kliekje risotto hebt. Als je gisteren geen risotto hebt gegeten is het wat meer werk, maar zeker de moeite waard! Je kunt bijvoorbeeld rode paprika’s vullen met de risotto van Lisette Kreischer of groene paprika’s vullen met onze rode bietenrisotto.',
cookingSteps: 'Verwarm de oven voor op grillstand, of bereid de barbecue voor. Zet de paprika’s neer (snij de onderkant recht als ze niet blijven staan) en snij de bovenkant eraf, zodat je die als een dekseltje kunt optillen. Verwijder de pitten en zaadlijsten. Vul de paprika’s met risotto en bestrooi met de pijnboompitten. Gril de paprika’s 10 minuten.',
tip: ' Vul aubergines met deze risotto. Snij ze in de lengte doormidden en hol ze uit, tot 1 centimeter van de rand. Het vruchtvlees kun je nog met de risotto laten meegaren. Vul de aubergine-schuitje met risotto en bestrooi met pijnboompitten.',
},
{
title: 'Frisse komkommer-cashewdip',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_26_WOE_LUNCH_Frisse-komkommerdip.jpg',
persons: 4,
ingredients: [
  { amount: 1,
    ingredient: 'komkommer, geschild en geraspt'},
  { amount: 150,
    measure: 'gr',
    ingredient: 'ongezouten cashewnoten, eventueel een uurtje geweekt in water'},
  { amount: 2,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'olijfolie'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'oregano'},
  { amount: 0.5,
    measure: 'theelepel',
    ingredient: 'zout'},
  { amount: 1,
    ingredient: 'citroen -sap'},
  { ingredient: 'Beetje peper'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'gesneden verse dille'},
],
lessThanFifteen: true,
gluten: true,
soy: true,
sugar: true,
spring: true,
summer: true,
greek: true,
breakfast: true,
lunch: true,
description: 'Deze dip is romig van de cashewnoten, maar toch verfrissend dankzij de komkommer. Als je het eenmaal hebt geproefd, wil je het overal wel bij eten!',
cookingSteps: 'Doe de komkommerrasp in een zeef en druk zoveel mogelijk vocht eruit. Dep eventueel af met keukenpapier. Doe de helft van de komkommer in de keukenmachine. Voeg de overige ingrediënten, behalve de dille, toe en pureer tot een fijne spread. Tenslotte roer je de rest van de komkommer en de dille erdoor.',
tip: 'deze dip is heerlijk bij Griekse of andere Mediterrane gerechten.',
},
{
title: 'Aardappelsalade',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_22_ZAT_LUNCH_Aardappelsalade.jpg',
persons: 4,
ingredients: [
  { amount: 800,
    measure: 'gr',
    ingredient: 'aardappelen, vastkokend'},
  { amount: 4,
    measure: 'stengels',
    ingredient: 'bleekselderij, in boogjes'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'veganaise'},
  { amount: 50,
    measure: 'ml',
    ingredient: 'soja- of rijstmelkroom'},
  { amount: 2,
    measure: 'theelepels',
    ingredient: 'mosterd'},
  { amount: 4,
    ingredient: 'zoetzure augurken, in blokjes'},
  { amount: 2,
    ingredient: 'groene paprikas, in reepjes'},
  { amount: 1,
    ingredient: 'rode ui, in halve ringetjes'},
],
gluten: true,
nuts: true,
lunch: true,
fifteenToThirty: true,
description: 'Een lekker plantaardig recept voor de traditionele Hollandse aardappelsalade.',
cookingSteps: 'Schil de aardappelen, snijd ze in plakjes en kook ze in ruim kokend water in 10 minuten beetgaar. Kook de bleekselderij de laatste 2 minuten mee. Giet af en laat iets afkoelen. Meng de mayonaise met de sojaroom, mosterd, augurk en 2 eetlepels van de azijn uit de pot augurken. Meng de dressing door de aardappel. Meng de paprika en ui door de aardappel­salade. Breng op smaak met peper en zout.',
tip: 'Maak eens aardappelsalade van zoete aardappel, ook wel bataat genoemd.',
},
{
title: 'Rijstwafels met jam',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/09/NOV_6_WOE_ONBIJT_Rijstwafels-met-jam.jpg',
persons: 1,
ingredients: [
  { ingredient: 'Zoveel rijstwafels als je lekker vindt'},
  { ingredient: 'Diverse soorten jam naar keuze'},
],
gluten: true,
soy: true,
sugar: true,
nuts: true,
lessThanFifteen: true,
breakfast: true,
snacks: true,
description: 'Niks zo eenvoudig als ‘s ochtends je bed uitkomen en gewoon even wat rijstwafels met jam besmeren!',
cookingSteps: 'Besmeer de rijstwafels met jam en geniet van een simpel ontbijtje.',
tip: 'Je kunt suikervrije jam en rijstwafels op basis van zilvervliesrijst nemen om langer verzadigd te blijven.',
},
{
title: 'Groene erwtendip',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_14_VRIJ_LUNCH_Groene-erwtendip.jpg',
persons: 4,
ingredients: [
  { amount: 75,
    measure: 'gr',
    ingredient: 'ongezouten amandelen'},
  { amount: 150,
    measure: 'gr',
    ingredient: 'tuinerwten (diepvries), ontdooid'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'vers geraspte gember'},
  { amount: 3,
    measure: 'eetlepels',
    ingredient: 'water'},
  { amount: 3,
    measure: 'eetlepels',
    ingredient: 'limoensap'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'olijfolie'},
  { amount: 1,
    measure: 'handje',
    ingredient: 'verse koriander'},
  { ingredient: 'Snuf zout en peper naar smaak'},
],
gluten: true,
soy: true,
sugar: true,
breakfast: true,
lunch: true,
brunch: true,
appetizer: true,
lessThanFifteen: true,
description: 'Deze dip is heerlijk romig door de amandelen. De tuinerwten geven het een intens groene kleur, zodat het er gelijk ook heel vega-verantwoord uitziet!',
cookingSteps: 'Doe de amandelen in de keukenmachine en maal fijn. Voeg de overige ingrediënten toe en pureer tot een egale dip. Indien nodig voeg je wat extra water toe. Breng op smaak met peper en zout. Lekker op knäckebröd, met nacho’s of op brood.',
tip: 'Heb je een feestje? Serveer deze dip met groentechips voor een gezonde snack.',
},
{
title: 'Banaan-kersen smoothie',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/01/FEB25-MAA-ONTBIJT-Banaan-kersensmoothie-683x1024.jpg',
persons: 1,
ingredients: [
  { amount: 2,
    ingredient: 'rijpe bananen'},
  { amount: 200,
    measure: 'gr',
    ingredient: 'diepvries kersen'},
  { amount: 400,
    measure: 'ml',
    ingredient: 'water of plantaardige melk naar keuze'},
],
drink: true,
breakfast: true,
gluten: true,
soy: true,
sugar: true,
nuts: true,
lessThanFifteen: true,
description: 'Deze smoothie is super makkelijk en toch zo ontzettend lekker. Door de banaan na het pellen in stukken te breken en in te vriezen, krijgt de smoothie een milkshake textuur. Daarnaast: hoe meer bruine stippen de banaan heeft, des te rijper de banaan is. Hierdoor is de banaan ook zoeter en zal deze meer smaak geven dan een groen-gele banaan.',
cookingSteps: 'Bereid de bananen een paar uur van te voren voor: Pel de bananen, breek ze in stukjes en vries ze in. Voeg alle ingrediënten in een blender en mix totdat alle ingrediënten gemalen zijn. Deze smoothie kan ook met een staafmixergemaakt worden, plaats dan alle ingrediënten in een maatbeker en mix met de staafmixer tot een smoothie.',
tip: 'Voeg ook eens een van de volgende lekkere ingrediënten toe aan deze smoothie: lijnzaad, vanille, notenpasta of pindakaas.',
},
{
title: 'Kokoslimoencupcakes',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_1_ZAT_BAK_Kokoslimoencupcakes.jpg',
persons: 3,
ingredients: [
  { amount: 125,
    measure: 'gr',
    ingredient: 'volkoren meel'},
  { amount: 1.5,
    measure: 'theelepels',
    ingredient: 'bakpoeder'},
  { amount: 1,
    measure: 'snufje',
    ingredient: 'zout'},
  { amount: 75,
    measure: 'gr',
    ingredient: 'geraspte kokos'},
  { amount: 75,
    measure: 'ml',
    ingredient: 'zonnebloemolie'},
  { amount: 150,
    measure: 'gr',
    ingredient: 'rietsuiker'},
  { amount: 250,
    measure: 'ml',
    ingredient: 'kokosmelk'},
  { amount: 25,
    measure: 'ml',
    ingredient: 'sojamelk'},
  { amount: 1,
    ingredient: 'sap en rasp van een kleine limoen'},
  { ingredient: 'geraspte kokos om te garneren'},
],
dessert: true,
nuts: true,
thirtyToOneHour: true,
description: 'Deze cupcakes zijn erg makkelijk te maken. De limoen en kokosmelk geven er zoveel smaak aan, dat je niet eens door hebt dat ze volkoren zijn!',
cookingSteps: 'Verwarm de oven voor op 175°C. Meng in een grote kom meel, bakpoeder, zout en de geraspte kokos. Klop, in een klein kommetje, de olie en de suiker samen tot de textuur iets lichter wordt. Giet dit suiker-oliemengsel in de kom met de droge ingrediënten. Voeg de limoenrasp, het limoensap, de kokosmelk en de sojamelk toe en roer voorzichtig tot alles vermengd is. Giet het beslag in 12 cupcakevormpjes. Bak de cupcakes zo’n 25 minuten, of tot een tandenstoker schoon uit een cupcake komt als je erin prikt. Garneer met wat geraspte kokos.',
tip: 'Kokosmelk over? Vries de rest in en gebruik het later als je maar weinig nodig hebt. In de vriezer kun je kokosmelk nog maanden bewaren.',
},
{
title: 'Hummuswrap met tomatentapenade',
picture: 'https://veganchallenge.nl/wp-content/uploads/2014/09/02_10_LUN_Hummuswrap-met-tomatentapenade.jpg',
persons: 2,
ingredients: [
  { amount: 230,
    measure: 'gr',
    ingredient: 'zongedroogde tomaten in olie'},
  { amount: 1,
    measure: 'flinke hand',
    ingredient: 'verse krulpeterselie'},
  { ingredient: 'olijfolie'},
  { amount: 2,
    ingredient: 'wraps'},
  { ingredient: 'Humus'},
  { amount: 0.25,
    ingredient: 'krop sla of andere rauwkost naar keuze'},
],
soy: true,
nuts: true,
lunch: true,
lessThanFifteen: true,
description: 'Deze wrap is makkelijk mee te nemen naar je werk of naar school, en is een welkome afwisseling van die bruine boterham!',
cookingSteps: 'Giet de tomaten af en doe samen met de peterselie in de keukenmachine. Laat deze draaien tot er een tapenade is ontstaan. Als de tapenade te droog is, kan je een scheutje olijfolie (of wat water, voor een magere versie) toevoegen. Besmeer de wraps met flink wat hummus en schep hier per wrap 3 eetlepels tapenade over. Beleg met de sla of eventuele andere rauwkost en rol de wrap op.',
tip: 'lekker met wat geroosterde pijnboompitten!',
},
{
title: 'Quinoa met paddenstoelen en bonen',
picture: 'https://veganchallenge.nl/wp-content/uploads/2014/10/29_10_DIN_Quinoa-met-paddenstoelen-en-bonen.jpg',
persons: 4,
ingredients: [
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'olie'},
  { amount: 1,
    ingredient: 'grote ui, gesnipperd'},
  { amount: 2,
    measure: 'teentjes',
    ingredient: 'knoflook, gesnipperd'},
  { amount: 10,
    ingredient: 'middelgrote champignons, gehalveerd en in plakjes'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'gerookt paprikapoeder'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'chilipoeder'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'gedroogde oregano'},
  { amount: 275,
    measure: 'gr',
    ingredient: 'quinoa, afgespoeld in een zeef'},
  { amount: 265,
    measure: 'gr',
    ingredient: 'zwarte bonen, afgespoeld'},
  { amount: 4,
    measure: 'eetlepels',
    ingredient: 'tomatenpuree'},
  { amount: 1,
    ingredient: 'groentebouillonblokje'},
  { amount: 900,
    measure: 'ml',
    ingredient: 'water'},
  { amount: 10,
    ingredient: 'kleine tomaatjes, in plakjes'},
  { ingredient: 'verse oregano of platte peterselie, optioneel'},
],
gluten: true,
soy: true,
nuts: true,
fifteenToThirty: true,
description: 'Dit Mexicaanse bonengerecht met quinoa krijgt door toevoegen van de champignons (of andere paddenstoelen!)  een aangenaam hersttintje.',
cookingSteps: 'Verhit de olie en fruit de ui, knoflook en champignons even aan. Voeg de kruiden toe en roerbak nog 2 minuten. Voeg de quinoa, zwarte bonen, tomatenpuree, verkruimelde bouillon en het water toe en breng zachtjes aan de kook. Kook tot de quinoa gaar is (kijk op de verpakking, dit duurt ongeveer 10 minuten). Voeg de plakjes tomaat toe en warm nog even door. Laat nog 2 minuten staan en roer door.',
tip: 'Serveer met gekookte sperziebonen en/of een (spinazie)salade. Probeer ook eens met andere paddenstoelen!',
},
{
title: 'Curry met kikkererwten en zoete aardappel',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_10_MAA_AVOND_Curry-met-kikkererwten-en-zoete-aardappel.jpg',
persons: 4,
ingredients: [
  { amount: 1,
    measure: 'Handje',
    ingredient: 'verse korianderblaadjes + extra voor decoratie'},
  { amount: 2,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { amount: 2,
    measure: 'cm',
    ingredient: 'verse gemberwortel, geschild'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'kurkuma'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'koriander'},
  { amount: 0.25,
    measure: 'eetlepel',
    ingredient: 'komijn'},
  { amount: 0.25,
    measure: 'eetlepel',
    ingredient: 'kaneel'},
  { amount: 0.5,
    measure: 'theelepel',
    ingredient: 'cayennepeper'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'water'},
  { amount: 3,
    measure: 'eetlepels',
    ingredient: 'olie'},
  { amount: 1,
    ingredient: 'ui'},
  { amount: 1,
    ingredient: 'rode paprika'},
  { amount: 400,
    measure: 'gr',
    ingredient: 'zoete aardappels, geschild (of gewone aardappels)'},
  { amount: 400,
    measure: 'gr',
    ingredient: 'kikkererwten'},
  { amount: 1,
    measure: 'klein blijke',
    ingredient: 'tomatenpuree'},
  { amount: 250,
    measure: 'gr',
    ingredient: 'couscous'},
],
lunch: true,
indian: true,
spring: true,
summer: true,
soy: true,
nuts: true,
thirtyToOneHour: true,
description: 'Hoewel veel currypasta’s vegan zijn, is zelf maken altijd leuker. Het duurt iets langer, maar als je weet dat je een gerecht vanaf de basis zelf hebt gemaakt, smaakt het gelijk veel lekkerder toch? Als je niet van verse koriander houdt, kun je het vervangen door peterselie of weglaten.',
cookingSteps: 'Meng de koriander, knoflook, gember, specerijen, water en 2 eetlepels van de olie in een keukenmachine of met een staafmixer. Hiermee maak je zelf een currypasta. Je kan ook een kant en klare pasta gebruiken voor een snelle curry. Snijd de ui, paprika en aardappels in blokjes. Verhit de olie en fruit de ui en paprika. Voeg de currypasta toe en bak even mee. Voeg de aardappel en uitgelekte kikkererwten toe, samen met de tomaten puree en ±500 ml water. Laat dit 25 minuten zachtjes doorkoken. Bereid intussen de couscous volgens de verpakking. Voeg op het bord de verse koriander toe.',
tip: 'Lekker met een frisse salade erbij.',
},
{
title: 'Noedelsoep met paksoi',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/05/JUN_22_ZAT_AVOND_Noedelsoep-met-paksoi.jpg',
persons: 4,
ingredients: [
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'olie'},
  { amount: 1,
    measure: 'teentjes',
    ingredient: 'knoflook, fijngesneden'},
  { amount: 1,
    ingredient: 'ui, in ringen'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'sambal oelek'},
  { amount: 3,
    measure: 'L',
    ingredient: 'groentebouillon'},
  { amount: 250,
    measure: 'gr',
    ingredient: 'mie (let op dat deze zonder ei is!)'},
  { amount: 1,
    measure: 'blijke',
    ingredient: 'bamboescheuten, uitgelekt'},
  { amount: 1,
    measure: 'struik',
    ingredient: 'paksoi, in dunne repen'},
  { amount: 15,
    measure: 'gr',
    ingredient: 'verse koriander, alleen de blaadjes'},
  { amount: 3,
    measure: 'eetlepels',
    ingredient: 'gebakken uitjes'},
],
appetizer: true,
lunch: true,
chinese: true,
thai: true,
vietnamese: true,
soy: true,
sugar: true,
nuts: true,
fifteenToThirty: true,
description: 'Eet je graag instant noodles? Dat kan nog steeds, er zijn verschillende soorten vegan noodles te verkrijgen. Kijk daarvoor eens rond bij de toko of Chinese supermarkt. Deze soep is een gezondere variant, met verse groenten en bamboescheuten. Ook een heerlijk tussendoortje!',
cookingSteps: 'Verhit de olie in een hapjespan en bak de knoflook, ui en sambal op laag vuur 5 min. tot de ui gaar is. Voeg de groentebouillon toe, breng aan de kook en voeg de miehoen toe. Laat 4 minuten wellen. Doe de bamboescheuten en de paksoi erbij. Laat 2 minuten koken tot de paksoi iets zachter, maar nog wel stevig is. Breng op smaak met peper en zout. Verdeel de soep over 4 kommen. Bestrooi met de koriander en uitjes.',
tip: 'deze noedelsoep kun je ook maken met andere soorten kool, zoals witte en savooie kool. Ook lekker om er gebakken ‘kip’stukjes van de Vegetarische Slager, of krokant gebakken tofureepjes door te doen!',
},
{
title: 'Chickpea Salad',
picture: 'https://veganchallenge.nl/wp-content/uploads/2016/04/Chickpea-Salad-2-730x450.jpg',
persons: 2,
ingredients: [
  { amount: 1,
    measure: 'cup',
    ingredient: 'gare kikkererwten'},
  { amount: 100,
    measure: 'ml',
    ingredient: 'kookwater van kikkererwten (aquafaba)'},
  { amount: 1,
    measure: 'eetlepel',
    ingredient: 'olie'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'kurkuma'},
  { amount: 1,
    measure: 'theelepel',
    ingredient: 'bonenkruid (of tijm)'},
  { amount: 6,
    ingredient: 'cherry tomaatjes, in kleine blokjes'},
  { amount: 1.5,
    measure: 'eetlepels',
    ingredient: 'olijfolie'},
  { amount: 1.5,
    measure: 'theelepels',
    ingredient: 'appelazijn'},
  { amount: 1,
    measure: 'theelepels',
    ingredient: 'gedroogde dille'},
  { ingredient: 'zout, peper'},
  { ingredient: 'verse basilicum of peterselie'},
],
brunch: true,
lunch: true,
breakfast: true,
appetizer: true,
autumn: true,
summer: true,
gluten: true,
soy: true,
sugar: true,
nuts: true,
lessThanFifteen: true,
description: 'Zo’n heerlijke ontdekking dat boontjeswater (aquafaba). Het kan merengue worden, cakes binden, en roerei vervangen. In deze salade zorgt het voor binding.',
cookingSteps: 'Plet de kikkererwten met een pureestamper. Verhit de olie in een koekenpan en voeg de kikkererwten, aquafaba, kurkuma en bonenkruid toe. Roerbak tot het bindt en een heel klein beetje bruin bakt. Het lijkt nu droog, maar ik beloof je dat dat niet zo is. Roer de tomaatjes, olijfolie, azijn, dille, zout en peper door elkaar en roer daar de kikkererwten door. Strooi de verse kruiden er over.',
tip: 'Ook zelfgekookte kikkererwten werken. Week ze, kook ze gaar en laat ze afkoelen. Ik kook meestal een pak per keer en verdeel de kikkererwten en het kookwater in porties. Met de rest van het kookwater maak je bijvoorbeeld *schuimpjes*',
},
{
title: 'Pasta arrabiata met walnotengehakt',
picture: 'https://veganchallenge.nl/wp-content/uploads/2016/12/FOTO-Pasta-arrabiata-met-walnotengehakt-645x450.jpg',
persons: 2,
ingredients: [
  { amount: 3,
    ingredient: 'gegrilde paprikas'},
  { amount: 0.5,
    ingredient: 'avocado'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'tomatenpuree'},
  { amount: 0.5,
    ingredient: 'rode peper'},
  { amount: 150,
    measure: 'gr',
    ingredient: 'volkorenpenne'},
  { ingredient: 'snufje zout'},
  { amount: 1,
    ingredient: 'ui'},
  { amount: 4,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'olijfolie'},
  { amount: 4,
    ingredient: 'tomaten'},
  { amount: 40,
    measure: 'gr',
    ingredient: 'walnoten'},
  { ingredient: 'zout en peper naar smaak'},
],
soy: true,
sugar: true,
italian: true,
lunch: true,
fifteenToThirty: true,
description: 'Een goede pasta is altijd lekker, maar deze pittige pasta is absoluut mijn favoriet. De klassieke combinatie van knoflook, chilipeper en tomaat om arrabiatasaus te maken is heerlijk. Ironish genoeg betekent het Italiaanse woord arrabiata in het Nederlands boos, verwijzend naar de pittigheid van het gerecht. Maar met de bite van het walnotengehakt en de romige textuur van de avocado word je er allesbehalve boos van! Dit recept is met toestemming overgenomen uit Kickstart van Lisa Steltenpool',
cookingSteps: 'Neem een keukenmachine of maatbeker met staafmixer en doe hier de gegrilde paprika, avocado, tomatenpuree en rode peper in. Mix tot een gladde saus en zet apart. Kook de volkorenpenne gedurende 7 minuten in kokend water met een snufje zout. Bewaar na het koken één koffie kopje aan kookvocht en giet de rest af. Snipper de ui en snijd de knoflook fijn. Verhit de olijfolie in een hoge koekenpan en fruit de ui en knoflook. Snijd ondertussen de tomaten in blokjes en doe deze in de pan. Hak de walnoten grof en voeg deze na 5 minuten samen met de apart gezette saus en het kookvocht toe. Meng het geheel goed. Meng ten slotte de penne met de saus en serveer in diepe borden. Voeg naar smaak zout en peper toe.',
tip: 'Garneer eventueel met geroosterde pijnboompitten en edelgistvlokken',
},
{
title: 'Taco’s met tofu gehakt, sla, tomaat & guacamole',
picture: 'https://veganchallenge.nl/wp-content/uploads/2012/12/FEB27-WOE-AVOND-tacos-met-tofu-gehakt-sla-en-guacamole1-730x450.jpg',
persons: 4,
ingredients: [
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'olie'},
  { ingredient: 'ui, fijngesneden'},
  { amount: 3,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { amount: 2,
    measure: 'pakjes',
    ingredient: 'tofu gehakt'},
  { amount: 70,
    measure: 'gr',
    ingredient: 'blikje tomatenpuree'},
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'paprikapoeder'},
  { amount: 2,
    measure: 'theelepels',
    ingredient: 'oregano'},
  { amount: 2,
    measure: 'theelepels',
    ingredient: 'komijn'},
  { amount: 1,
    measure: 'theelepels',
    ingredient: 'zout'},
  { amount: 50,
    measure: 'ml',
    ingredient: 'water'},
  { amount: 1,
    ingredient: 'rijpe avocado'},
  { amount: 50,
    measure: 'ml',
    ingredient: 'water'},
  { amount: 0.5,
    measure: 'theelepels',
    ingredient: 'zout'},
  { amount: 0.25,
    measure: 'theelepels',
    ingredient: 'cayennepeper'},
  { amount: 1,
    ingredient: 'limoensap'},
  { amount: 1,
    measure: 'handje',
    ingredient: 'verse koriander'},
  { amount: 1,
    ingredient: 'kropsla, fijngesneden'},
  { amount: 4,
    ingredient: 'tomaten, in schijfjes'},
],
mexican: true,
lunch: true,
sugar: true,
nuts: true,
fifteenToThirty: true,
description: 'Nog een heerlijke klassieker uit de Mexicaanse keuken. Varieer zelf met verschillende soorten rauwkost. Guacamole is in supermarkten kant- en klaar verkrijgbaar, maar check wel de ingrediënten want deze is lang niet altijd vegan. Zelf maken kan natuurlijk ook; het is niet moeilijk en bovendien vaak nog lekkerder ook!',
cookingSteps: 'Verwarm de oven voor op 125 graden en verwarm de taco’s dan zo’n 15 minuten. Verwarm de olie in een ruime koekenpan en fruit de ui 5 minuten. Pers de knoflook erboven uit (snijd ook de restjes fijn!) en bak dit een minuut mee. Doe het tofu-gehakt erbij en bak dit 5 minuten aan. Voeg de tomatenpuree, paprikapoeder, oregano, komijn, zout en water toe, en bak dit nog zo’n 10 minuten door. Als het te droog wordt voeg je nog wat water toe. Doe de avocado in de keukenmachine, samen met het water, het zout, de cayennepeper, het limoensap, en de verse koriander – als je die gebruikt. Pureer dit tot guacamole. Vul de taco schelpen met het gehakt, sla, tomaat en wat guacamole.',
tip: 'Serveer er eventueel nog salsa bij.',
},
{
title: 'Wraps met kidneybonen, pompoen, avocado & salsa',
picture: 'https://veganchallenge.nl/wp-content/uploads/2012/12/FEB01-VRIJ-AVOND-Wraps-met-pompoen-2-730x450.jpg',
persons: 4,
ingredients: [
  { amount: 1,
    ingredient: 'middelgrote pompoen'},
  { amount: 1,
    measure: 'theelepels',
    ingredient: 'olie'},
  { amount: 1,
    ingredient: 'ui'},
  { amount: 3,
    measure: 'teentjes',
    ingredient: 'knoflook'},
  { amount: 50,
    measure: 'ml',
    ingredient: 'water'},
  { amount: 400,
    measure: 'gr',
    ingredient: 'tomatenblokjes'},
  { amount: 1,
    measure: 'theelepels',
    ingredient: 'komijn'},
  { amount: 1,
    measure: 'theelepels',
    ingredient: 'oregano'},
  { amount: 1,
    measure: 'theelepels',
    ingredient: 'paprikapoeder'},
  { amount: 0.5,
    measure: 'theelepels',
    ingredient: 'cayennepeper'},
  { ingredient: 'Zout naar smaak'},
  { amount: 400,
    measure: 'gr',
    ingredient: 'kidneybonen'},
  { amount: 8,
    ingredient: 'tortilla wraps'},
  { amount: 1,
    ingredient: 'rijpe avocado'},
  { amount: 300,
    measure: 'gr',
    ingredient: 'milde of hete salsa'},
],
mexican: true,
lunch: true,
soy: true,
sugar: true,
nuts: true,
thirtyToOneHour: true,
description: 'Wraps met een lekkere kruidige vulling. De pompoen en kidneybonen maken het een stevig gerecht. Je kunt zowel een oranje pompoen als een flespompoen gebruiken.',
cookingSteps: 'Spoel de pompoen goed af; de pompoen hoeft namelijk niet geschild te worden, op lelijke plekjes in de schil na. Snijd met een groot mes voorzichtig de top van de pompoen af en snijd de pompoen door midden. Snijd de helften nog eens door en verwijder de zaden en draden met een lepel. Maak blokjes van het vruchtvlees en snijd de ui fijn. Verhit de olie in een grote pan. Fruit de ui ongeveer 5 minuten. Pers de knoflook hierboven uit en bak nog één minuut mee. Voeg de pompoenblokjes en het water toe en laat dit ongeveer 10 minuten stoven. Verwarm intussen de oven voor op 100 ºC of gebruik later in het recept de magnetron om de tortilla’s op te warmen. Voeg de tomatenblokjes, komijn, oregano, paprikapoeder, cayennepeper en zout naar smaak aan de pompoen toe. Roer door en laat nog 10 minuten stoven. Laat het blik kidneybonen uitlekken en voeg de bonen toe. Verwarm deze nog een paar minuten mee.Warm de wraps ongeveer een minuut op in de voorverwarmde oven zodat ze warm en soepel worden. Snijd ondertussen de avocado in plakken: snijd deze door de helft, verwijder de pit en trek de schil eraf, snijd dan de plakken. Serveer de tortilla’s met de groenten/bonenvulling, schijfjes avocado en salsa.',
tip: 'In plaats van de ovenstand kun je de wraps ook eerst vullen en vervolgens 5 minuten onder de voorverwarmde gril zetten. Ze krijgen dan een knapperige bovenkant.',
},
{
title: 'Vegan Mac & Cheese',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/02/Vegan-Mac-n-Cheese-pasta-met-kaassaus.jpg',
persons: 4,
ingredients: [
  { amount: 35,
    measure: 'gr',
    ingredient: 'edelgist'},
  { amount: 35,
    measure: 'gr',
    ingredient: 'bloem'},
  { amount: 2,
    measure: 'theelepels',
    ingredient: 'knoflookpoeder'},
  { amount: 2,
    measure: 'theelepels',
    ingredient: 'uienpoeder'},
  { amount: 0.25,
    measure: 'theelepels',
    ingredient: 'zout'},
  { ingredient: 'snufje kurkuma'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'bouillonpoeder (of 1 blokje)'},
  { amount: 500,
    measure: 'ml',
    ingredient: 'water'},
  { amount: 1,
    measure: 'theelepels',
    ingredient: 'mosterd'},
  { amount: 250,
    measure: 'gr',
    ingredient: 'volkoren macaroni'},
  { amount: 500,
    measure: 'gr',
    ingredient: 'broccoli'},
],
lunch: true,
soy: true,
nuts: true,
lessThanFifteen: true,
description: 'Mac & Cheese is een typische Amerikaanse hap, maar ook in Nederland is macaroni met kaas populair. Deze veganistische versie is net anders, maar zeker net zo lekker. Edelgist kun je in natuurvoedingswinkels vinden.',
cookingSteps: 'Meng edelgist, bloem, knoflook- en uienpoeder, zout, kurkuma en bouillonpoeder in een sauspan. Voeg water toe en klop met de garde de klontjes eruit. Breng aan de kook en laat 5 minuten zachtjes borrelen. Laat de saus indikken en voeg op het einde mosterd toe. Snij de broccoli in roosjes en stoom het binnen 8 minuten gaar. De pasta moet ook 8 minuten koken, ideaal om de broccoli erboven te stomen!',
tip: 'Ben je dol op dit recept? Maak dan wat extra saus en vries het in (bijvoorbeeld in ijsblokvormpjes). Zo heb je altijd wat achter de hand voor als je dit gerecht snel klaar wil hebben.',
},
{
title: 'Pesto sandwich',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/01/FEB20-WOE-LUNCH-Pesto-sandwich.jpg',
persons: 1,
ingredients: [
  { amount: 2,
    measure: 'sneetjes',
    ingredient: 'volkorenbrood'},
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'basilicumpesto zonder kaas'},
  { amount: 3,
    ingredient: 'cherry tomaatjes'},
  { amount: 8,
    measure: 'plakjes',
    ingredient: 'komkommer'},
  { ingredient: 'pijnboompitten (optioneel)'},
],
soy: true,
sugar: true,
nuts: true,
lunch: true,
italian: true,
lessThanFifteen: true,
description: 'Makkelijk, gezond en lekker zijn de kenmerken van dit broodje! Pesto zonder kaas vind je onder andere bij Albert Heijn, van Puur&Eerlijk.',
cookingSteps: 'Besmeer de sneetjes brood met de basilicumpesto en beleg met komkommer en cherry tomaatjes. Rooster eventueel een handje pijnboompitten in een droge koekenpan, en maak je broodje hiermee helemaal af.',
tip: 'Probeer ook eens tomatentapenade of olijventapende op brood. Vergeet niet de ingrediënten te checken, want met name olijventapenade bevat soms ansjovis.',
},
{
title: 'Saffraan couscous met sinaasappel',
picture: 'https://veganchallenge.nl/wp-content/uploads/2016/12/Saffraan-couscous-met-sinaasappel-609x450.jpg',
persons: 4,
ingredients: [
  { amount: 250,
    measure: 'gr',
    ingredient: 'couscous'},
  { amount: 3,
    ingredient: 'saffraandraadjes of 1 el kurkuma'},
  { amount: 1,
    ingredient: 'sinaasappel'},
  { amount: 3,
    ingredient: 'abrikozen'},
  { amount: 1,
    ingredient: 'ubergine'},
  { amount: 50,
    measure: 'gr',
    ingredient: 'kappertjes'},
  { amount: 10,
    ingredient: 'geroosterde amandelen'},
  { amount: 30,
    measure: 'gr',
    ingredient: '(gele) rozijnen'},
  { amount: 1,
    ingredient: 'citroen'},
  { amount: 2,
    ingredient: 'bosuitjes'},
  { amount: 1,
    ingredient: 'bosje munt'},
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'olijfolie extra vierge'},
  { amount: 12,
    ingredient: 'vegan groenteballetjes'},
],
soy: true,
sugar: true,
lunch: true,
italian: true,
fifteenToThirty: true,
description: 'Saffraan couscous. Dat klinkt misschien heel fancy en lastig te maken. Niets is minder waar! Saffraandraadjes koop je bij de reguliere supermarkten en zorgen ervoor dat de couscous mooi geel wordt. De combinatie van gegrilde aubergine, zilte kappertjes en zoete sinaasappel is heerlijk. Je kunt er wat vegan groenteballetjes aan toevoegen voor extra vulling. Dit recept is met toestemming overgenomen uit Lisa Goes Vegan van Lisa Stel. Foto credit: Puur by Dyana',
cookingSteps: 'Laat de rozijnen 5 minuten wellen in warm water. Snijd de aubergine in dunne plakken (1/2 cm) en leg ze in je tostiapparaat of grillpan totdat ze bruine strepen krijgen. Bereid ondertussen de couscous zoals op de verpakking staat en voeg de saffraandraadjes bij het kokend water toe. Roer de couscous los met een vork. Rasp de schil van de sinaasappel en citroen en schep dit door de couscous. Snijd de gegrilde aubergine klein, de bosuitjes in ringen, de abrikoos in partjes de verse munt fijn. Hak de geroosterde amandelen in stukjes. Meng de aubergine, bosui, abrikozen, munt, amandelen en kappertjes bij de couscous. Schep alles om met de extra vierge olijfolie en het sap van de sinaasappel. Giet de rozijnen af en voeg deze ook toe. Snijd de groenteballetjes door de helft en bak deze 7 minuten bruin. Voeg deze toe aan de couscous. Schep alles in diepe borden en garneer met verse muntblaadjes.',
tip: 'Glutenvrij? Vervang de couscous door quinoa of boekweit en de groenteballetjes door gebakken tempeh.',
},
{
title: 'Geroosterde pompoensalade',
picture: 'https://veganchallenge.nl/wp-content/uploads/2013/11/pompoensalade-730x450.jpe',
persons: 4,
ingredients: [
  { amount: 600,
    measure: 'gr',
    ingredient: 'pompoen'},
  { amount: 4,
    measure: 'eetlepels',
    ingredient: 'olijfolie'},
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'gedroogde tijm'},
  { ingredient: 'Peper en zout'},
  { amount: 75,
    measure: 'gr',
    ingredient: 'rucola'},
  { ingredient: 'rode ui, in blokjes'},
  { amount: 8,
    ingredient: 'zongedroogde tomaten, in reepjes'},
  { amount: 3,
    measure: 'eetlepels',
    ingredient: 'pompoenpitten'},
  { amount: 50,
    measure: 'gr',
    ingredient: 'amandelschaafsel'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'balsamico azijn'},
],
gluten: true,
soy: true,
sugar: true,
lunch: true,
appetizer: true,
italian: true,
autumn: true,
thirtyToOneHour: true,
description: 'Deze salade schreeuwt herfst: niet alleen met de zachte, prachtig oranje pompoen, maar ook dankzij de pompoenpitten en aardse rucola smaak. Wist je dat je pompoenpitten in grote zak goedkoper kunt kopen bij de biologische winkel? Ze zijn erg gezond en niet alleen een goede toevoeging in salades, maar ook heerlijk door soepen.',
cookingSteps: 'Verwarm de oven voor op 180 graden en bekleed een bakplaat met bakpapier. Snijd de pompoen in parten, verwijder het vruchtvlees (schillen is niet nodig). Leg de pompoenparten op de bakplaat en besprenkel met 2 eetlepels olie, tijm en wat peper en zout. Rooster de pompoen ongeveer 25 minuten. Doe de rucola in een schaal en schep de ui, zongedroogde tomaten, pompoenpitten en amandelschaafsel erdoor. Leg de pompoenparten erop en besprenkel met de rest van de olijfolie en de balsamico azijn.',
tip: 'Maak een dubbele portie geroosterde pompoen en gebruik de rest voor de pompoenhummus morgen!',
},
{
title: 'Hollandsche Appeltaart',
picture: 'https://veganchallenge.nl/wp-content/uploads/2012/12/FEB16-ZAT-BAK-Hollandsche-appeltaart1-730x450.jpg',
persons: 4,
ingredients: [
  { amount: 375,
    measure: 'gr',
    ingredient: 'bloem'},
  { amount: 4,
    measure: 'theelepels',
    ingredient: 'bakpoeder'},
  { amount: 225,
    measure: 'gr',
    ingredient: 'vloeibare margarine (bak- en braad)'},
  { amount: 200,
    measure: 'gr',
    ingredient: 'lichte bruine basterdsuiker'},
  { amount: 1,
    measure: 'sakje',
    ingredient: 'vanillesuiker'},
  { amount: 0.25,
    measure: 'theelepels',
    ingredient: 'zout'},
  { amount: 3,
    measure: 'eetlepels',
    ingredient: 'sojamelk'},
  { amount: 1.5,
    measure: 'kg',
    ingredient: 'appels'},
  { amount: 1,
    ingredient: 'citroen'},
  { amount: 20,
    measure: 'gr',
    ingredient: 'suiker'},
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'kaneel'},
  { amount: 60,
    measure: 'gr',
    ingredient: 'rozijnen'},
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'custardpoeder of maïzena'},
],
dessert: true,
autumn: true,
nuts: true,
moreThanOneHour:  true,
description: 'Een heerlijke ouderwetse appeltaart, van een moderne grootmoeder. Deze taart bevat namelijk geen ei, zoals in het originele recept. Dit recept is voor een taart van ongeveer 24 centimeter doorsnede, dus pas eventueel de hoeveelheden aan als je een grotere taart maakt.',
cookingSteps: 'Voeg in een mengkom of kom van een keukenmachine bloem, bakpoeder,basterdsuiker, vanillesuiker en zout samen en meng het door elkaar. Voeg de vloeibare margarine en sojamelk toe en kneed het tot een samenhangend deeg, dat niet plakt. Verpak het deeg in plasticfolie en leg het in de koelkast. Schil de appels en snijd ze in stukjes. Doe de stukjes in een bak en besprenkel tussendoor steeds met een beetje citroensap. Pas op dat er geen citroenpitjes tussen de appels komen. Voeg vervolgens de suiker, kaneel, rozijnen (die niet geweekt hoeven worden) en custardpoeder of maïzena toe en meng goed. Zet het appelmengsel in de koelkast. Verwarm de oven voor op 180 °C. Bekleed de onderkant van een taartvorm met bakpapier en vet de randen in met vloeibare margarine of olie. Haal het deeg uit de koelkast. Bestuif het aanrecht met bloem en rol ongeveer 0.66 tot 0.75 van de deegbal uit tot ongeveer een halve centimeter dikte. Bedek hiermee de bodem en randen van de vorm. Doe het appelmengsel in de vorm en rol vervolgens de rest van het deeg uit. Snijd hieruit 8 stroken van ongeveer 1,5 cm breed en leg deze kruislings over de taartvulling heen. Leg als laatste een strook langs de rand van de taart. Bestrijk de bovenkant van de taart met sojamelk voor een mooie goudbruine glans. Bak de taart ongeveer 1 uur in het midden van de oven. Laat ongeveer een uur afkoelen om de taart steviger te laten worden.',
tip: 'Ook lekker met andere vruchten als vulling, bijvoorbeeld appel in combinatie met bosbessen. Bosbessen zijn in de winter ingevroren te koop.',
},
{
title: 'Mummyworteltjes',
picture: 'https://veganchallenge.nl/wp-content/uploads/2016/10/Mummyworteltjes-1024x1024.jpg',
persons: 5,
ingredients: [
  { amount: 6,
    ingredient: 'wortels'},
  { amount: 125,
    measure: 'ml',
    ingredient: 'sojasaus'},
  { amount: 2,
    measure: 'eetlepels',
    ingredient: 'azijn'},
  { amount: 1,
    measure: 'eetlepels',
    ingredient: 'olie'},
  { amount: 1,
    measure: 'theelepels',
    ingredient: 'gerookt paprikapoeder'},
  { amount: 0.5,
    measure: 'theelepels',
    ingredient: 'knoflookpoeder'},
  { amount: 0.25,
    measure: 'theelepels',
    ingredient: 'gemberpoeder'},
  { amount: 0.25,
    measure: 'theelepels',
    ingredient: 'peper'},
  { ingredient: 'Olie om te bakken'},
  { amount: 270,
    measure: 'gr',
    ingredient: 'Tante Fanny bij Jumbo of AH vers bladerdeeg eigen merk'},
  { ingredient: 'Mosterd of mayonaise voor oogjes'},
],
halloween: true,
snack: true,
autumn: true,
nuts: true,
moreThanOneHour:  true,
description: 'Vier je graag op een mens- én diervriendelijke manier Halloween maar wil je toch graag griezelige hapjes op tafel zetten? Probeer dan deze mummyworteltjes eens! De (vloeibare) rook maakt ze extra smaakvol.',
cookingSteps: 'Maak de wortels schoon en snijd ze door midden. Maak ondertussen de marinade door sojasaus, azijn, olie, liquid smoke, knoflookpoeder, gemberpoeder en peper te mengen. Doe dit ideaal gezien in een afsluitbare plastic zak, of als je die niet hebt in een middelgrote schaal. Leg de wortels in de marinade en laat ze zeker 3 uur marineren. Zorg er in het geval van een plastic zak voor dat er zo min mogelijk lucht in de zak zit. Haal de wortels uit de marinade en bak ze in een koekenpan in wat olie voor zo’n 10 minuten. Haal de wortels uit de pan en laat ze even afkoelen. Verwarm ondertussen de oven voor op 200 graden. Snijd dunne stroken van het bladerdeeg, bijvoorbeeld met een pizzaroller. Wikkel iedere wortel in het bladerdeeg, en houd een ruimte open voor de oogjes. Leg de ingepakte wortels op een bakplaat bekleed met bakpapier en bak ze voor 15 tot 25 minuten, totdat ze goudbruin zijn.',
},
];

// Seed the user and recipes!
const feathersClient = feathers();

feathersClient
  .configure(hooks())
  .configure(rest('http://localhost:3030').superagent(superagent))
  .configure(auth());

feathersClient.service('users').create(user)
  .then(() => {
    feathersClient.authenticate({
      strategy: 'local',
      email: user.email,
      password: user.password
    })
      .then(() => {
        recipes.map((recipe) => {
          feathersClient.service('recipes').create(recipe)
            .then((result) => {
              console.log('Recipe seeded...', result.title);
            }).catch((error) => {
              console.error('Error seeding recipe!', error.message);
            });
        });
      })
      .catch(function(error){
        console.error('Error authenticating!', error);
      });
  })
  .catch(function(error) {
    console.error('Error creating user!');
  });
